### ISSUE TITLE
需要专门弄个页面来写入暴力膜

### ISSUE THREAD

**Issue by dsh0416** [hczhcz/the-elder-is-excited#6]
否则载入个项目页得慢成什么样了，多节约点时间贡献出来啊。。。

**Comment by hczhcz** [comment]
是不是网页没被 gzip……这种数据模式，压缩率应该不知道高到哪里去才对

要不我去折叠一下 markdown，这样就能跑得比谁都快了（

**Comment by dsh0416** [comment]
中间的点点点我还以为是什么高级的程序生成的。。。结果。。。

**Comment by hczhcz** [comment]
一年折叠一次懒得自动化（
