### ISSUE TITLE
10月27和28呢？！

### ISSUE THREAD

**Issue by m4sop2** [hczhcz/the-elder-is-excited#9]
怎么回事？！长者GG了？还是作者水表了？！

**Comment by Tao-Quixote** [comment]
你们这些程序员，年后集中枪毙，谁也跑不了

**Comment by Tao-Quixote** [comment]
呃，有大佬可以讲一下 README 文件开头的那堆符号是什么意思吗？

**Comment by hczhcz** [comment]
@Tao-Quixote 是那段众所周知的视频的截图，用vlc的ASCII art渲染出来的效果

**Comment by m4sop2** [comment]
其实可以用ACSII字符画生成器搞一个
<hr>
你介个项目开的吼啊，每天都续一下
